# Generated by Django 5.2 on 2025-04-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_givepoint_date_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/achievements/')),
                ('name', models.CharField(max_length=255)),
                ('point_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
