# Generated by Django 5.2 on 2025-04-24 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_achievement_mentor_birthday_mentor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='selected_option',
            new_name='answer_option',
        ),
    ]
