# Generated by Django 5.2 on 2025-04-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_selected_option_studentanswer_answer_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
